package com.mohamed265.toggltest.eu.europa.ec.taxud.vies.services.checkvat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.mohamed265.toggltest.eu.europa.ec.taxud.vies.services.checkvat.types.ObjectFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "checkVatPortType", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat")
@XmlSeeAlso({ ObjectFactory.class })
public interface CheckVatPortType {

	/**
	 * 
	 * @param valid
	 * @param address
	 * @param name
	 * @param countryCode
	 * @param requestDate
	 * @param vatNumber
	 */
	@WebMethod
	@RequestWrapper(localName = "checkVat", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", className = "eu.europa.ec.taxud.vies.services.checkvat.types.CheckVat")
	@ResponseWrapper(localName = "checkVatResponse", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", className = "eu.europa.ec.taxud.vies.services.checkvat.types.CheckVatResponse")
	public void checkVat(
			@WebParam(name = "countryCode", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", mode = WebParam.Mode.INOUT) Holder<String> countryCode,
			@WebParam(name = "vatNumber", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", mode = WebParam.Mode.INOUT) Holder<String> vatNumber,
			@WebParam(name = "requestDate", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", mode = WebParam.Mode.OUT) Holder<XMLGregorianCalendar> requestDate,
			@WebParam(name = "valid", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", mode = WebParam.Mode.OUT) Holder<Boolean> valid,
			@WebParam(name = "name", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", mode = WebParam.Mode.OUT) Holder<String> name,
			@WebParam(name = "address", targetNamespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", mode = WebParam.Mode.OUT) Holder<String> address);

}
